export const productSub = {
  airpods: [
    'AirPods 1Gen',
    'AirPods 2Gen',
    'AirPods 3Gen',
    'AirPods Pro',
    'AirPods Max',
  ],
  applewatch: [
    'Series 1',
    'Series 2',
    'Series 3',
    'Series 4',
    'Series 5',
    'Series 6',
    'SE',
    'Series 7',
  ],
  ipad: ['iPad', 'iPad Air', 'iPad mini', 'iPad Pro', 'iPad Pro(12.9)'],
  iphone: [
    'iPhone 6',
    'iPhone 6+',
    'iPhone 6s',
    'iPhone 6s+',
    'iPhone 7',
    'iPhone 7+',
    'iPhone 8',
    'iPhone 8+',
    'iPhone X',
    'iPhone XR',
    'iPhone Xs',
    'iPhone Xs Max',
    'iPhone 11',
    'iPhone 11 Pro',
    'iPhone 11 Pro Max',
    'iPhone 12 mini',
    'iPhone 12',
    'iPhone 12 Pro',
    'iPhone 12 Pro Max',
    'iPhone 13 mini',
    'iPhone 13',
    'iPhone 13 Pro',
    'iPhone 13 Pro Max',
    'iPhone SE',
    'iPhone SE Gen2',
    'iPhone SE Gen3',
  ],
  mac: ['Mac mini', 'Mac Studio', 'Mac Pro', 'iMac'],
  macbook: ['MacBook Air', 'MacBook Pro'],
};
