# This Dockerfile builds the API only.
FROM python:3.9
WORKDIR /app

RUN apt update

COPY backend/. .
RUN pip install -r ./requirements.txt
ENV PYTHONUNBUFFERED=0
EXPOSE 50000
CMD ["gunicorn", "-b", ":50000", "app:application", "-k", "gevent", "--worker-connections", "4096"]
